import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'
import './globals.css'
import { App } from '~/app/_/App'
import { Toaster } from '~/components/ui/Toaster'

const kanit = Kanit({
    subsets: ['latin', 'latin-ext', 'vietnamese', 'thai'],
    weight: ['100', '400', '700', '800', '900'],
})

export const metadata: Metadata = {
    title: 'Awesome Nextjs Template',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={kanit.className}>
                <App>{children}</App>
                <Toaster />
            </body>
        </html>
    )
}
